### PR TITLE
SubTask -> Task migration release

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

It contains @ptwu's change on the subtask -> task frontend migration and a script to migrate existing DB data. The script is already run.

I also merged in the order change in #636, forgetting this release PR still exists... This PR sorts the tasks in the order of [group, repeating, one-time], then by order. Please make sure it doesn't break as well.

### Test Plan 

Please help test on staging site to ensure nothing breaks, including but not limited to:

- creating tasks
- editing subtask from focus view/future view
- deleting individual subtask in focus view/future view
- focus/complete individual subtask or entire task in focus/future view

### CODE REVIEW

**Review by ptwu — CHANGES_REQUESTED** [review]
clear focus is broken right now, giving me this error.

image

Seems to be caused by this function in `actions.ts`. Unsure why the `commit()` is getting called early.

https://github.com/cornell-dti/samwise/blob/d8b344c3b6291026c457d6711e91941cf96a6ee2/frontend/src/firebase/actions.ts#L480

**Review by ptwu — APPROVED** [review]
lgtm

**Review by meganyin13 — COMMENTED** [review]
Really great work master hacker Peter but we should check repeating tasks. I noticed:
1. completing/deleting a subtask of repeating task automatically applies that for all tasks of that template. I think we should be forking it?
2. Pinning it results in the error bear page :(

Wow I also now can't get back in my samwise-dev account cuz it's stuck on error bear page lol I think some data is corrupted.

**Review by SamChou19815 — COMMENTED** [review]
oof, looks like we have some tasks that only have children???

Screen Shot 2020-11-08 at 23 31 06

octocat-astonished

**Comment by ptwu** [comment]
> oof, looks like we have some tasks that only have children???
> 
> Screen Shot 2020-11-08 at 23 31 06
> 
> octocat-astonished

Yikes. did you run the script on prod already?

**Comment by SamChou19815** [comment]
> > oof, looks like we have some tasks that only have children???
> > Screen Shot 2020-11-08 at 23 31 06
> > octocat-astonished
> 
> Yikes. did you run the script on prod already?

no, it's from staging

**Comment by SamChou19815** [comment]
@ptwu looks like this is the code to blame for broken repeating tasks:

https://github.com/cornell-dti/samwise/blob/86ca1f254f15e17063ddd169bacc95281acfdb86/frontend/src/components/TaskView/FutureView/FutureViewSubTask.tsx#L22-L47

you should not assume it's one time task

**Comment by ptwu** [comment]
> > > oof, looks like we have some tasks that only have children???
> > 
> > 
> > Yikes. did you run the script on prod already?
> 
> no, it's from staging

Maybe I need to look at the script one more time. It might actually only be updating the children to the new format and not moving all the rest of the data.

**Review by meganyin13 — COMMENTED** [review]
I am seeing that for group tasks, subtasks aren't showing on the group view task card (although it does show up on personal view). This is not push-blocking though.

**Comment by ptwu** [comment]
PR should be ready for review now.

**Review by ptwu — APPROVED** [review]
Made sure to delete old tasks and played with new ones: both one-time and repeating. Things seem to be working as expected.

**Review by meganyin13 — APPROVED** [review]
looks very good! I've tested one time and repeating tasks and deleting/pinning/completing them and forking. Things seem to work. Also the group tasks subtask issue I mentioned earlier is also master so definitely not push blocking. Great job master hacker Peter! 
shipit_parrot

Ordering also looks good. I think we should disable dragging on group tasks because right now I can drag group tasks and one time tasks into group tasks section (although it doesn't actually get dropped there.)

**Review by jason-tung — COMMENTED** [review]
samwisebug
can't change task completion from future view

**Review by ptwu — APPROVED** [review]

**Comment by jason-tung** [comment]
samwisebug2

quickly clicking breaks marking repeating tasks as complete

**Comment by ptwu** [comment]
> samwisebug2
> 
> quickly clicking breaks marking repeating tasks as complete

I was able to reproduce this bug in prod. I think we can separately make a PR to fix this in a different release.

**Review by jason-tung — APPROVED** [review]

**Review by meganyin13 — APPROVED** [review]
Amazing work master hacker mvp dev peter!! 
shipit_parrot

**Pull request merged**
