### PR TITLE
September Release

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

Release everything we did in September and first 3 days of October into prod.

Notable changes:

- [ui] @IshikaJain fixed accessibility issues for date, tag, and focus picker
- [group-task, ui] @meganyin13 removed the incorrect repeating task icon from group task in future view.
- [group-task] Several updates to group task by (@SamChou19815, @pihucode, @ptwu). They are gated so just check site without group tasks still work.
- [chore] Updated course json multiple times and the update frequency is reduced by @meganyin13. Now it has prelim exams thanks to @ptwu .
- [infra] Migrated frontend toolchain from CRA to next.js

### Test Plan 

Staging

### CODE REVIEW

**Review by ptwu — COMMENTED** [review]
image
after selecting a value for Focus/Tag/DatePicker, the X button seems a bit off. Here's what it looks like in prod:
image

This may have been caused by #556.

**Review by meganyin13 — COMMENTED** [review]
I think these class codes text should be center aligned? Not seeing it's fixed in #564  
image

**Comment by SamChou19815** [comment]
> I think these class codes text should be center aligned? Not seeing it's fixed in #564
> class picker

@IshikaJain

**Review by ptwu — DISMISSED** [review]
tested with staging on master (https://samwise-dev.firebaseapp.com/) and everything seems to be working！

**Review by jason-tung — DISMISSED** [review]

**Review by ptwu — APPROVED** [review]

**Review by meganyin13 — APPROVED** [review]
Things seem to work, small nit I think there's a little more left and right padding on the add tag button 

staging:
image
production:
image

This is very nitpicky so I don't think this is push-blocking 😅

**Review by pihucode — APPROVED** [review]

**Pull request merged**
