### PR TITLE
Merge master into release to deploy new version

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

Notable changes:

- New splash screen
- No more save for complete and focus in any view

### Test Plan 

See https://samwise-dev.firebaseapp.com

### CODE REVIEW

**Comment by SamChou19815** [comment]
Please only approve this once you play with the staging site extensively and think it's good.

**Comment by mt-xing** [comment]
Repeating tasks are still gated behind a flag, so bugs specific to repeating tasks shouldn't be considered push blocking as long as they don't impact normal functionality.

**Comment by SamChou19815** [comment]
> Why are the next and previous arrows in 5 day view gone?

Confirmed. Likely a regression introduced in #302.

**Comment by SamChou19815** [comment]
Add WIP to title to prevent merging

**Comment by meganyin13** [comment]
I can push in a CSS hack. In `FutureViewControl.tsx`, I set `const offset = -10;` and the arrows are back.

**Pull request merged**
