### PR TITLE
Avoid using position: absolute to construct TaskCreator. Close #618

### LINKED ISSUE #618: [code-quality] TaskCreator css code is terrible
Looks like we added a bunch of `positive: absolute` for elements that don't really need them. As a result, the code is very fragile:

Screen Shot 2020-10-24 at 17 46 31

Looks like all we want to do is to workaround the issue that the `input` is the first element within form.

https://github.com/cornell-dti/samwise/blob/c24cc059431f61a12a22dbf870e4785905840bea/frontend/src/components/TaskCreator/index.tsx#L490-L507

Then we started to use `position: absolute` so that we can actually place something before the `input` 😢 🤦

### PR DESCRIPTION
**Pull request by SamChou19815**
### Summary 

After #617, #628, #630, #644, we are finally in a good position to fix the bad code in `TaskCreator`.

As a recap, the existing code is only `position: absolute` to hack code positions of varies components of `TaskCreator`, merely to overcome the difficulty to place some content before the `input` without input appearing after those content in JSX.

This PR almost completely rewrites the css related to positioning in `TaskCreator`. I also moved some jsx code around to make the layout make more sense.

### Test Plan 

Old:
old

New personal:
new-personal

New group:
new-group

### CODE REVIEW

**Review by meganyin13 — COMMENTED** [review]
Something is a little off here... the cursor for the main task text & assign to search bar doesn't start at the left most side of the box (as it does on prod):
main-task-text
assign-to-searchbar

Also, the whole TaskCreator seems to have shifted down which is fine for group view but personal view is shifted a little too low 😕

**Comment by SamChou19815** [comment]
> Something is a little off here... the cursor for the main task text & assign to search bar doesn't start at the left most side of the box (as it does on prod):
> 
> main-task-text
> 
> assign-to-searchbar
> 
> Also, the whole TaskCreator seems to have shifted down which is fine for group view but personal view is shifted a little too low 😕

Good catch. I will fix these when I have time. To all the future reviewers, this is a tricky refactor and needs more careful reviews!

**Review by meganyin13 — COMMENTED** [review]
When comparing prod and staging side by side things are still a little bit shifted which is fine I think
prod-staging side by side

But the class tags are now a little too wide:
this PR
this PR
Prod
prod

Also this PR adds some space between `Add Subtasks (optional)` text and the below subtext
line break

**Review by meganyin13 — COMMENTED** [review]
I think the `add class` and `add date` bubbles are shifted a little too much to the right?
this PR:
image
prod:
image

Also, I think there's actually less empty space at the bottom of TaskCreator which I think is better design 😄

**Review by meganyin13 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
