### PR TITLE
Frontend Stylistic Fixes

### PR DESCRIPTION
**Pull request by mt-xing**
- Overflow hidden on the page, removed shadow behind progress tracker
- Add class box clears after adding class

### CODE REVIEW

**Comment by mt-xing** [comment]
It seems that while deleting the tag selected in add task no longer crashes, any active tasks tagged with that tag will still cause a crash. To the reviewer: don't let me merge this branch without fixing that.

**Comment by SamChou19815** [comment]
> It seems that while deleting the tag selected in add task no longer crashes, any active tasks tagged with that tag will still cause a crash. To the reviewer: don't let me merge this branch without fixing that.

@mt-xing I think it's a regression. It happens before when I rewrite the backend I forget to also modify all tasks with that tag. Do you want me to fix in my branch?

**Comment by mt-xing** [comment]
@SamChou19815 If you get a chance, that would be ideal.

**Comment by SamChou19815** [comment]
> @SamChou19815 If you get a chance, that would be ideal.

I will likely to push the changes in minutes. After that, you can review my pull request and merge the changes to your branch.

**Comment by mt-xing** [comment]
So due to my flow type checker breaking after the latest merge, I've been unable to get the tag fix working within this branch by tonight. Instead, we can just merge the changes I already have as is.

**Pull request merged**
