### PR TITLE
Group Tasks Frontend SideBar, People, Task Queue

### PR DESCRIPTION
**Pull request by meganyin13**
### Summary 

In this pull request, I begin building out the static layout of SideBar, People, and Task Queue sections of Group View. The plan is to build out the static version while Jason works on the backend, so all data is hardcoded. 

This pull request is the first step towards implementing Group View

WORK PLAN
- [x] implement SideBar
- [x] add interactivity elements to SideBar (hover, click, active behaviors)
- [x] bring SettingsButton to SideBar (some issues with SettingsPage, though)
- [x] add New Group dropdown functionality
- [x] implement People section
- [x] add Task Queue section (using current FocusView tasks as placeholder)
- [x] gate this feature
- [x] fix SideBar Settings page

### Test Plan 

Play with staging.
I will also try to write some snapshot tests.

### Notes
Merged in Sam's `GateKeeper` functionality from #484. To enable group tasks open console and type `GateKeeper.enableGroupTask()`. To disable, enter `GateKeeper.disableGroupTask()`.

### CODE REVIEW

**Comment by mt-xing** [comment]
The CSS needs a lot of work, and also the Settings page is broken.

**Comment by meganyin13** [comment]
@SamChou19815 there seems to be an issue with the way CSS is interpreted on staging. Unsure if this is caused by #482. 
Layout on staging:
image
Layout on local:
image
@ptwu checked out my branch locally and the CSS looked fine 😕

**Comment by SamChou19815** [comment]
@meganyin13 source map shouldn't affect css. It's JS only.

**Comment by mt-xing** [comment]
image
Is there supposed to be an icon in here?

**Comment by mt-xing** [comment]
image
hmm

**Pull request merged**
